### ISSUE TITLE
Missing addParameterValue in Assay

### ISSUE THREAD

**Issue by feserm** [IPK-BIT/isa4J#16]
When building samples for the assay file, there is not option to add Parameter Values. Instead you are able to add Factor Values.

https://ipk-bit.github.io/isa4j/javadoc/de/ipk_gatersleben/bit/bi/isa4j/components/Sample.html
https://isa-specs.readthedocs.io/en/latest/isatab.html#assay-table-file

**Comment by Thyra** [comment]
Hey, Parameters are only ever attached to Processes, not Process Inputs or Outputs like Sources or Samples. Samples instead can carry Characteristics and Factors. From the link you provided:

> A `Sample` MUST be provided as the first node in the experimental graph, indicated with the column heading `Sample Name`.
> 
> `Protocol REF` columns MUST be used to indicate `Process` nodes, with values referencing protocols declared in the Investigation file. The `Protocol REF` column MAY be qualified with `Parameter Value [<parameter term>]`

It is even more clear from the JSON schemas (https://isa-specs.readthedocs.io/en/latest/isajson.html#sample-schema-json):
```
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title" : "ISA sample schema",
    "description" : "JSON-schema representing a sample in the ISA model. A sample represents a major output resulting from a protocol application other than the special case outputs of Extract or a Labeled Extract.",
    "type": "object",
    "properties" : {
        "@id": { "type": "string", "format": "uri" },
        "name" : { "type" : "string" },
        "characteristics" : {
            "type" : "array",
            "items" :  {
                "$ref": "material_attribute_value_schema.json#"
            }
        },
        "factorValues" : {
            "type" : "array",
            "items" : {
                "$ref" : "factor_value_schema.json#"
            }
        },
        "derivesFrom": {
            "type" : "array",
            "items" : {
                "$ref": "source_schema.json#"
            }
        }
    },
    "additionalProperties": false
}
```

Please reopen the issue if I misunderstood you.
